name: trancend
description: "Hypnoisis + Therapy"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.11
  auto_size_text: ^3.0.0
  badges: ^3.1.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  get: ^4.6.6
  get_it: ^8.0.3
  cloud_firestore: ^5.6.0
  firebase_core: ^3.9.0
  firebase_analytics: ^11.4.1
  firebase_auth: ^5.4.0
  firebase_ui_firestore: ^1.7.0
  firebase_storage: ^12.4.0
  flutter_launcher_icons: ^0.14.2
  flutter_svg: ^2.0.16
  flutter_staggered_animations: ^1.1.1
  google_sign_in: ^6.1.6
  recase: ^4.1.0
  stacked_services: ^1.6.0
  observable_ish: ^6.0.5
  remixicon: ^1.3.0
  shared_preferences: ^2.5.2
  simple_shadow: ^0.3.1
  sign_in_with_apple: ^6.1.4
  simple_animations: ^5.1.0
  supercharged: ^2.1.1
  http: ^1.2.2
  flutter_facebook_auth: ^6.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  just_audio: ^0.9.43
  ffmpeg_kit_flutter: ^6.0.3
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  flutter_colorpicker: ^1.0.3
  simple_eye_dropper:
    git:
      url: https://github.com/satoshiiorg/simple_eye_dropper.git
  inner_shadow_widget: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.4
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  shaders:
    - shaders/pond_effect.frag

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/color_schemes/
    - assets/color_schemes/candy_colors.json
    - assets/color_schemes/earth_colors.json
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
    - family: TitilliumWebLight
      fonts:
        - asset: assets/fonts/TitilliumWeb-Light.ttf
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf

scripts:
  postinstall: bash scripts/install-hooks.sh