name: trancend
description: "Hypnoisis + Therapy"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.11
  auto_size_text: ^3.0.0
  badges: ^3.1.2
  clay_containers: ^0.3.4
  get: ^4.6.6
  get_it: ^8.0.3
  cloud_firestore: ^5.6.0
  firebase_core: ^3.9.0
  firebase_ui_firestore: ^1.7.0
  flutter_launcher_icons: ^0.14.2
  flutter_svg: ^2.0.16
  flutter_staggered_animations: ^1.1.1
  remixicon: ^1.3.0
  simple_animations: ^5.1.0
  supercharged: ^2.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
